# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/message
Accept: application/json
Content-Type: application/json

{
  "id": 3,
  "username": "unauthorized user",
  "message_text": "Subidubi",
  "create_time": "2024.01.25T22:00:00"
}

### Send a form with form text fields for register user
POST http://127.0.0.1:8000/register
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"
Content-Type: text/plain

password
--WebAppBoundary
Content-Disposition: form-data; name="username"
Content-Type: text/plain

telcselek
--WebAppBoundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

titok
--WebAppBoundary--
Content-Disposition: form-data; name="email"
Content-Type: text/plain

telcselek@email.com
--WebAppBoundary--
Content-Disposition: form-data; name="fullname"
Content-Type: text/plain

Telcs Elek
--WebAppBoundary--

### Send a form with form text fields for login
POST http://127.0.0.1:8000/login
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="username"
Content-Type: text/plain

johndoe
--WebAppBoundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

secret
--WebAppBoundary--

###

POST http://127.0.0.1:8000/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZXhwIjoxNzM4MTk4ODcxfQ.30MliCDtOtoSg7oHjFyzVQNifHItt41mnKxX91aXKLM
Accept: application/json
Content-Type: application/json

{
  "role": "system",
  "username": "telcselek",
  "message_text": "42"
}

###

POST http://127.0.0.1:8000/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZWxjc2VsZWsiLCJleHAiOjE3MzgxOTMwNjV9.vD4dbTZ5QODuwiXJR4VOyBYQEtqBImOClkBXXi0cjl4
Accept: application/json
Content-Type: application/json

{
  "username": "telcselek",
  "message_text": "itt járt Mátyás király..."
}

###

GET http://127.0.0.1:8000/messages
Accept: application/json

###

GET http://127.0.0.1:8000/messages?limit=1&offset=1
Accept: application/json

###

GET http://127.0.0.1:8000/messages?user=other user
Accept: application/json

###

GET http://127.0.0.1:8000/messages?user=telcselek
Accept: application/json

###

GET http://127.0.0.1:8000/message/2
Accept: application/json

###

DELETE http://127.0.0.1:8000/message/1
Accept: application/json

###

DELETE http://127.0.0.1:8000/message/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZXhwIjoxNzM4MTkwMzUwfQ.g1TGB6ovuxiPR3sZ46KogcDJRH_RTdv4XJvSqhRYxU8
Accept: application/json

###

GET http://127.0.0.1:8000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZXhwIjoxNzM4MTkwMzUwfQ.g1TGB6ovuxiPR3sZ46KogcDJRH_RTdv4XJvSqhRYxU8
Accept: application/json
